version: "2.1"
services:

  wildfly:
    image: service-1
    ports:
      - "8080:8080"
      - "9990:9990"

  db:
    image: postgres:13.3-alpine
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=labs
    ports:
      - "5432:5432"

  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "4567:4567"